### ISSUE TITLE
Bonnier News (BN) Dagens Nyheter - TBE issues on iOS SDK [Email: "Re: Liquid Cinema SDK testing - DN"]

### ISSUE THREAD

**Issue by benkwak** [DEEPinc/LC_iOS_SDK_issues#3]
Markus Ekblad <markus.ekblad@pija.se>:

Few issues - A couple of examples:

1, On iOS The TBE sound only seems to play if the video has been paused/resumed once, or by changing to VR mode (which pauses/resumes the video too).
2, On iOS, Trying to load for example this HLS stream http://video-cdn.dn.se/M/V/J/l/JlsYysilUiOviEg4ouq10g_auto_hls.ssl.m3u8?v=1&token=0a77d743b068be54eea1f I get an error, "Sorry, the video you are looking for is not found. Return to the previous page." Error code -2. But the sound (video sound, there is no tbe file for the stream) starts playing in the background and can't be stopped.

**Comment by markusekblad** [comment]
@joelriley-deepinc @ScottNovakowski The issue with TBE requiring a pause / resume is still present in 1.3

**Comment by ScottNovakowski** [comment]
Issue resolved
